spring:
  application:
    #    name: user-service
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    #    url: jdbc:postgresql://localhost:5432/Bank
    url: ${SPRING_DATASOURCE_URL}
    #    username: postgres
    username: ${SPRING_DATASOURCE_USERNAME}
    #    password: qrrqrr
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  output:
    ansi: enabled

server:
  #  port: 8081
  port: ${SPRING_LOCAL_PORT_LOCAL}

eureka:
  client:
    fetch-registry: false
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
      # defaultZone: http://localhost:8761
    healthcheck:
      enabled: true
