spring:
  application:
    name: deposit-service
  datasource:
    url: jdbc:postgresql://localhost:5432/Bank
    username: postgres
    password: qrrqrr
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  output:
    ansi: enabled

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/


